# Есептер Апта 14
## 🟢 1-деңгей. Негізгі (Basic)
### Тапсырма 1. Тензорлармен жұмыс

In [1]:
import torch 
import torch.nn as nn 

In [5]:
# 1 
zeros_ten = torch.zeros(3, 4)
print(zeros_ten)

# 2 
ones_ten = torch.ones(4,3)
print(ones_ten)

# 3 
result = torch.matmul(zeros_ten, ones_ten)
print(result)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Тапсырма 2. Арифметикалық операциялар

In [7]:
a = torch.tensor([2.0, 4.0, 6.0])
b = torch.tensor([1.0, 3.0, 5.0])

sum =   a + b 
mul = a * b 
dot = torch.dot(a,b)

print(f' Sum: {sum}\n Multiple: {mul}\n Dot: {dot}')

 Sum: tensor([ 3.,  7., 11.])
 Multiple: tensor([ 2., 12., 30.])
 Dot: 44.0


### Тапсырма 3. Shape және reshape


In [10]:
rand_tensor = torch.rand(2, 6)

reshaped = rand_tensor.reshape(3,4)

transposed = reshaped.T

print(f" Random: \n{rand_tensor}\n\n Reshaped: \n{reshaped}\n\n Tranposed: \n{transposed}")

 Random: 
tensor([[0.2564, 0.1169, 0.9227, 0.7680, 0.5558, 0.6978],
        [0.9841, 0.7175, 0.1872, 0.5723, 0.1187, 0.9990]])

 Reshaped: 
tensor([[0.2564, 0.1169, 0.9227, 0.7680],
        [0.5558, 0.6978, 0.9841, 0.7175],
        [0.1872, 0.5723, 0.1187, 0.9990]])

 Tranposed: 
tensor([[0.2564, 0.5558, 0.1872],
        [0.1169, 0.6978, 0.5723],
        [0.9227, 0.9841, 0.1187],
        [0.7680, 0.7175, 0.9990]])


## 2-деңгей. Орташа (Intermediate)

### Тапсырма 4. Автоматты дифференция