In [1]:
import numpy as np 

In [2]:
# 1 

A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

In [3]:
A + B

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [4]:
A - B 

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [5]:
A * B

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [7]:
A @ B 

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [9]:
# 2
# Scalar 
scalar_m = np.dot(A,B)
scalar_m

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [8]:
norm1 = np.linalg.norm(A)
norm2 = np.linalg.norm(B)

In [10]:
cos_theta = scalar_m / (norm1 * norm2)

In [11]:
theta_rad = np.arccos(cos_theta, -1.0, 1.0)

In [12]:
theta_deg = np.degrees(theta_rad)
print(theta_deg)

[[83.95767158 85.16937141 86.37890909]
 [72.85824205 75.98917193 79.07792939]
 [61.03923882 66.42182152 71.59151983]]


In [15]:
# 3
determinant = np.linalg.det(B)
determinant

0.0

In [17]:
M = np.array([
    [4, 2],
    [1, 3]
])
inverse_matrix = np.linalg.inv(M)
inverse_matrix

array([[ 0.3, -0.2],
       [-0.1,  0.4]])

In [19]:
eigen_values, eigen_vectors = np.linalg.eig(M)
print(eigen_values)

[5. 2.]


In [20]:
# 4 
sample = np.random.rand(1000)

In [21]:
np.mean(sample)

0.4956574948376983

In [22]:
variance = np.var(sample)

In [23]:
std_dev = np.std(sample)

In [24]:
# 5
data = np.array([5, 10, 15, 20, 25])

In [27]:
np.min(data)

5

In [28]:
np.max(data)

25

In [30]:
min_max_normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
min_max_normalized

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
mu = np.mean(data)
sigma = np.std(data)
z_score_normalized = (data - mu) / sigma

In [32]:
print("\nZ-score Normalized:")
print("   Mean (μ):", mu, " | Stn (σ):", sigma)
print("   Result (new μ ≈ 0, new σ ≈ 1):", z_score_normalized)


Z-score Normalized:
   Mean (μ): 15.0  | Stn (σ): 7.0710678118654755
   Result (new μ ≈ 0, new σ ≈ 1): [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
