# Python-дағы ОББ, ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттер, NumPy кіріспе (массивтер, векторизация, негізгі операциялар)

1. Мақсат                                                                        
Python тілінде объектілі-бағытталған бағдарламалау (ОББ), ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттермен жұмыс, сондай-ақ NumPy кітапханасындағы негізгі операцияларды меңгеру.

# Есеп 1.1:

---
Кітап (Kitap) атты класс құрыңыз. Бұл кластың атауы (atau) және авторы (avtory) деген екі атрибуты болуы керек.\
__init__ әдісін қолданып, кітап атауын және авторын инициализациялаңыз.\
Класс ішінде кітап_туралы_мәлімет (kitap_turaly_malimet) атты әдіс жасаңыз. Бұл әдіс "Кітап: [Атауы], Авторы: [Авторы]" деген мәтінді консольға шығаруы керек.\
Осы класстан бір нысан (объект) жасаңыз және кітап_туралы_мәлімет әдісін шақырыңыз.

In [1]:
class Kitap:
    def __init__(self, atau, avtory):
        self.atau = atau
        self.avtory = avtory

    def kitap_turaly_malimet(self):
        print(f"Кітап: [{self.atau}], Авторы: [{self.avtory}]")

    
black_words_42 = Kitap('Абайдың қара сөздері', 'Абай Құнанбайұлы')

In [2]:
black_words_42.kitap_turaly_malimet()

Кітап: [Абайдың қара сөздері], Авторы: [Абай Құнанбайұлы]


# Есеп 2.1:

---

numpy кітапханасын np ретінде импорттаңыз.\
1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз.\
3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз. Мысалы, 1-ден 9-ға дейінгі сандарды пайдаланыңыз.\
Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз.

In [1]:
import numpy as np 

In [2]:
arr_a = np.array(range(1, 10))
arr_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr_b = arr_a.reshape(3,3)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr_b.shape

(3, 3)

In [9]:
arr_b.dtype

dtype('int32')

# Есеп 3.1:


---

numpy-ді np ретінде импорттаңыз.\
Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін (vec1 және vec2) жасаңыз (мысалы, 1-ден 10-ға дейінгі).\
Векторизацияны қолдана отырып (циклсіз):
- Екі массивті қосыңыз (vec1 + vec2).
- Әрбір элементтің квадратын есептеңіз (vec1 ** 2).
vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз.\

Барлық нәтижелерді консольға шығарыңыз.

In [10]:
import numpy as np 

In [17]:
vec1 = np.random.randint(1,10, size=5)
ver2 = np.random.randint(10,20, size=5)

In [18]:
vec1 + ver2

array([21, 20, 20, 26, 23])

In [19]:
vec1 ** 2 

array([64,  4, 36, 49, 81])

In [20]:
vec1.mean()

6.4

In [22]:
vec1

array([8, 2, 6, 7, 9])

In [21]:
vec1.max()

9