# Үй Жұмысы

Бұл үй жұмысы сіздің Сызықтық Алгебра, Ықтималдықтар Теориясы және Деректерді Алдын Ала Өңдеу салаларындағы базалық біліміңізді тексеруге арналған. Барлық тапсырмалар қарапайым және NumPy кітапханасы арқылы орындалады.

In [1]:
import numpy as np
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
# Қажетті кітапханаларды импорттау

---

## Тапсырма 1: Деректердің Орташа Мәнін Табу (Статистика)

### Кейс: Студенттердің Емтихан Ұпайлары

Машиналық оқыту курсы бойынша 5 студенттің қорытынды емтиханнан алған ұпайлары берілген:\$$\text{Ұпайлар} = [75, 82, 68, 91, 79, 95, 89, 70, 92]$$

**Тапсырма:**
Осы ұпайлардың **орташа мәнін (mean)** есептеңіз.
Орташа мән (мю) $$\mu$$ бұл деректер жинағының орталық нүктесін көрсетеді.

In [3]:
# Тапсырма 1-ді орындау үшін кодты осы жерге енгізіңіз
scores = np.array([75, 82, 68, 91, 79])

# Орташа мәнді есептеу
average_score = scores.mean()
average_score

79.0

---

## Тапсырма 2: Екі Векторды Қосу (Сызықтық Алгебра)

### Кейс: Екі Түрлі Өлшем

Сізде екі қатар деректер бар, олар Машиналық оқыту моделінің екі түрлі мүмкіндігін білдіреді:
1. Бірінші мүмкіндік (Vector A): $$\mathbf{A} = \begin{pmatrix} 1.5 \\ 2.0 \\ 0.5 \end{pmatrix}$$ Екінші мүмкіндік (Vector B): $$\mathbf{B} = \begin{pmatrix} 3.0 \\ 1.0 \\ 2.5 \end{pmatrix}$$
**Тапсырма:** Екі векторды қосып, **$$\mathbf{C} = \mathbf{A} + \mathbf{B}$$** қосынды векторын табыңыз.

In [4]:
# Тапсырма 2-ні орындау үшін кодты осы жерге енгізіңіз
A = np.array([1.5, 2.0, 0.5])
B = np.array([3.0, 1.0, 2.5])

# Векторларды қосу
C = A + B
C


array([4.5, 3. , 3. ])

---

## Тапсырма 3: Скалярлық Көбейту (Сызықтық Алгебра)

### Кейс: Мүмкіндікті Күшейту

Берілген $v$ векторы моделіңіздің бір мүмкіндігін білдіреді, бірақ сіз оның әсерін 3 есе күшейткіңіз келеді.\n$$v = \begin{pmatrix} 2 \\ -1 \\ 5 \end{pmatrix}$$**Тапсырма:**

$v$ векторын **скаляр $$\lambda = 3$$** санына көбейтіп, жаңа $$\mathbf{u} = 3\mathbf{v}$$ векторын табыңыз.

In [5]:
# Тапсырма 3-ті орындау үшін кодты осы жерге енгізіңіз
v = np.array([2, -1, 5])
scalar = 3

# Скалярлық көбейтуді орындау
u = v * 3 
u 


array([ 6, -3, 15])

---

## Тапсырма 4: Жай Ықтималдық (Ықтималдықтар Теориясы)

### Кейс: Деректерді Жіктеу Қателігі

Модель 100 деректер нүктесін жіктеді. Нәтижелер *Дұрыс жіктелгендер саны: 92* Қате жіктелгендер саны: 8

**Тапсырма:** Кездейсоқ таңдалған деректер нүктесінің **дұрыс жіктелу ықтималдығын** ($$P(\text{Дұрыс})$$) есептеңіз.

In [6]:
# Тапсырма 4-ті орындау үшін кодты осы жерге енгізіңіз
total_points = 100
correctly_classified = 92

# Дұрыс жіктелу ықтималдығын есептеу
probability_correct = correctly_classified / total_points
probability_correct


0.92

---

## Тапсырма 5: Min-Max Нормализациясы (Деректерді Өңдеу)

### Кейс: Атрибуттық Масштабтау

Бір атрибуттың мәндері берілген:$$\text{Мәндер} = [10, 20, 50, 40, 30]$$

**Тапсырма:**
Берілген мәндерді **Min-Max нормализациясын** қолданып, $$[0, 1]$$ диапазонына масштабтаңыз.

In [8]:
# Тапсырма 5-ті орындау үшін кодты осы жерге енгізіңіз
data_points = np.array([10, 20, 50, 40, 30]).reshape(-1, 1)

# MinMaxScaler-ді инициализациялау
scaler = MinMaxScaler()

# Деректерді түрлендіру
data_normalized = scaler.fit_transform(data_points)
data_normalized

array([[0.  ],
       [0.25],
       [1.  ],
       [0.75],
       [0.5 ]])